services:
  server1:
    image: nginx:1.26.1
    ports:
      - 8091:80
    volumes:
      - ./docker/server1/html/index.html:/usr/share/nginx/html/index.html

  server2:
    image: nginx:1.26.1
    ports:
      - 8092:80
    volumes:
      - ./docker/server2/html/index.html:/usr/share/nginx/html/index.html

  reverse-proxy:
    image: nginx:1.26.1
    ports:
      - 443:443
    volumes:
      - ./docker/reverse-proxy/reverse-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./docker/reverse-proxy/certificate/server.crt:/etc/nginx/ssl/server.crt
      - ./docker/reverse-proxy/certificate/server.key:/etc/nginx/ssl/server.key
    extra_hosts:
      - host.docker.internal:${HOST_IP}
