services:
  server1:
    image: nginx:1.26.1
    ports:
      - 8091:80
    volumes:
      - ./docker/server1/.htpasswd:/etc/nginx/.htpasswd
      - ./docker/server1/conf.d/:/etc/nginx/conf.d/
      - ./docker/server1/html/index.html:/usr/share/nginx/html/index.html

  server2:
    image: nginx:1.26.1
    ports:
      - 8092:80
    volumes:
      - ./docker/server2/.htpasswd:/etc/nginx/.htpasswd
      - ./docker/server2/conf.d/:/etc/nginx/conf.d/
      - ./docker/server2/html/index.html:/usr/share/nginx/html/index.html

  reverse-proxy:
    image: nginx:1.26.1
    ports:
      - 443:443
    volumes:
      - ./docker/reverse-proxy/certificate/server.crt:/etc/nginx/ssl/server.crt
      - ./docker/reverse-proxy/certificate/server.key:/etc/nginx/ssl/server.key
      - ./docker/reverse-proxy/conf.d/:/etc/nginx/conf.d/
      - ./docker/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - host.docker.internal:${HOST_IP}
