services:
  server1:
    image: nginx:1.26.1
    ports:
      - 8091:80
    volumes:
      - ./docker/server1/html/index.html:/usr/share/nginx/html/index.html

  server2:
    image: nginx:1.26.1
    ports:
      - 8092:80
    volumes:
      - ./docker/server2/html/index.html:/usr/share/nginx/html/index.html

  reverse-proxy:
    image: nginx:1.26.1
    ports:
      - 8090:80
    volumes:
      - ./docker/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - host.docker.internal:${HOST_IP}
